enquetes_main_accueil:
    pattern:  /
    defaults: { _controller: EnquetesMainBundle:Accueil:index }
    
enquetes_main_utilisateur:
    pattern:  /utilisateur
    defaults: { _controller: EnquetesMainBundle:Utilisateur:utilisateur }

    
enquetes_main_creation:
    pattern:  /creation
    defaults: { _controller: EnquetesMainBundle:Creation:creation }
    
enquetes_main_creation_step2:
    pattern:  /creation/{id}/etape2/
    defaults: { _controller: EnquetesMainBundle:Creation:etape2 }
    requirements:
      id: \d+
    
enquetes_main_resultat:
    pattern:  /resultat
    defaults: { _controller: EnquetesMainBundle:Resultat:resultat }
  

enquetes_main_ajout_question:
    pattern:  /ajout/{form}
    defaults: { _controller: EnquetesMainBundle:Creation:ajout }
    requirements:
      form: \d+ 

enquetes_main_suppresion:
    pattern:  /suppression/{id}
    defaults: { _controller: EnquetesMainBundle:Suppresion:suppression }
    requirements:
      id: \d+
      
enquetes_main_rechercherRep:
    pattern: /finalresult/{id}
    defaults: { _controller: EnquetesMainBundle:Resultat:rechercherRep }
    requirements:
      id: \d+

enquetes_main_menu:
    pattern: /menu
    defaults: { _controller: EnquetesMainBundle:Resultat:menu }
    
enquetes_main_edition_compte:
    pattern:  /editioncompte
    defaults: { _controller: EnquetesMainBundle:Creation:compte }
      
enquetes_main_repondre:
    pattern:  /repondre/{id}
    defaults: { _controller: EnquetesMainBundle:Repondre:repondre }
    requirements:
       id: \d+

enquetes_main_modifier:
    pattern:  /modifier/{id}
    defaults: { _controller: EnquetesMainBundle:Creation:modifier }
    requirements:
       id: \d+

#    
#enquetes_main_utilisateur_compte:
#    pattern:  /utilisateur_compte/{id}
#    defaults: { _controller: EnquetesMainBundle:Utilisateur_Compte:utilisateur_compte }
#    requirements:
#    id: \d+
