parameters:
#    enquetes_main.example.class: Enquetes\MainBundle\Example

services:
#    enquetes_main.example:
#        class: %enquetes_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
