enquetes_main:
    resource: "@EnquetesMainBundle/Resources/config/routing.yml"
    prefix:   /
login:
    pattern:   /
    defaults:  { _controller: EnquetesMainBundle:Accueil:index }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout
