enquetes_main:
    resource: "@EnquetesMainBundle/Resources/config/routing.yml"
    prefix:   /
login:
    pattern:   /login
    defaults:  { _controller: EnquetesMainBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout
