security:
    encoders:
        Enquetes\MainBundle\Entity\Utilisateur:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: EnquetesMainBundle:Utilisateur, property: username }
        main:
            entity: { class: EnquetesMainBundle:Utilisateur, property: username }
    firewalls:
        admin_area:
            pattern:    ^/admin
            http_basic: ~
        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }