package introavecswing.inscription;

import java.util.GregorianCalendar;

/**
 * Etape 7 : ajout de la classe Inscrit
 */
public class InscriptionEtape7 extends javax.swing.JFrame {

    /**
     * Creates new form Inscription
     */
    public InscriptionEtape7() {
        initComponents();

        setLocationRelativeTo(null);
        setTitle("Inscription (étape 7)");

        // --- Date du jour pour selectionner dans les listes
        GregorianCalendar gc = new GregorianCalendar();
        int jourActuel = gc.get(GregorianCalendar.DAY_OF_MONTH);
        int moisActuel = gc.get(GregorianCalendar.MONTH);
        int anneeActuelle = gc.get(GregorianCalendar.YEAR);

        // --- Les jours
        for (int i = 1; i <= 31; i++) {
            jComboBoxJours.addItem(i);
        }
        jComboBoxJours.setSelectedItem(jourActuel);

        // Les mois
        // Tableau associatif des mois ou pas !!!
        String[] tMois = {"Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"};
//        this.jComboBoxMois.addItem("<<mois>>");
//        for (int i = 0; i < tMois.length; i++) {
//            this.jComboBoxMois.addItem(tMois[i]);
//        }
        for (String mois : tMois) {
            this.jComboBoxMois.addItem(mois);
        }
        jComboBoxMois.setSelectedIndex(moisActuel);

        // --- Les annees
        int i = 2000;
        while (i <= anneeActuelle) {
            jComboBoxAnnees.addItem(i);
            i++;
        }

        // Init a la date du jour
        jComboBoxAnnees.setSelectedItem(anneeActuelle);

    }  /// CONSTRUCTEUR

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();
        jTextFieldPseudo = new javax.swing.JTextField();
        jTextFieldMDP = new javax.swing.JTextField();
        jTextFieldAge = new javax.swing.JTextField();
        jComboBoxJours = new javax.swing.JComboBox();
        jComboBoxMois = new javax.swing.JComboBox();
        jComboBoxAnnees = new javax.swing.JComboBox();
        jButtonAnnuler = new javax.swing.JButton();
        jButtonValider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pseudo");

        jLabel2.setText("MDP");

        jLabel3.setText("Age");

        jLabel4.setText("Date d'inscription");

        jLabelMessage.setText("Message");

        jTextFieldPseudo.setText("Tintin");

        jTextFieldMDP.setText("mdpMDP123");

        jTextFieldAge.setText("18");

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3))
                            .addGap(65, 65, 65)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonAnnuler)
                                    .addGap(23, 23, 23)
                                    .addComponent(jButtonValider))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldMDP, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPseudo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(175, 175, 175)))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxJours, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxMois, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxAnnees, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxJours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAnnees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnnuler)
                    .addComponent(jButtonValider))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        jLabelMessage.setText("Vous avez annulé !");
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
//        jLabelMessage.setText("Votre âge est de " + jTextFieldAge.getText());

        boolean lbOK = true;
        StringBuilder lsbMessage = new StringBuilder();
        lsbMessage.append("<html>");

        if (this.jTextFieldPseudo.getText().trim().equals("")) {
            lsbMessage.append("Pseudo obligatoire<br>");
            lbOK = false;
        } else {
            // * 1,n
            // + 0,n
            // Commence par des lettres
            // et se termine par eventuellement des chiffres
            String lsMotifPseudo = "^[A-Za-z-]+[0-9]*$";
            if (jTextFieldPseudo.getText().matches(lsMotifPseudo)) {
                lsbMessage.append("Pseudo OK<br>");
            } else {
                lsbMessage.append("Pseudo KO<br>");
                lbOK = false;
            }
        }

        if (this.jTextFieldMDP.getText().trim().equals("")) {
            lsbMessage.append("MDP obligatoire<br>");
            lbOK = false;
        } else {
            // --- Le mot de passe
            // String lsMotifMDP = "([A-Z]{1,})|([a-z]{1,})|([0-9]{1,})";
            // Entre 6 et 10 caractères
            // Au moins 1 lettre majuscule, 1 lettre minuscule, 1 chiffre
            String lsMotifMDP = "^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{6,10}$";
            if (jTextFieldMDP.getText().matches(lsMotifMDP)) {
                lsbMessage.append("MDP OK<br>");
            } else {
                lsbMessage.append("MDP KO<br>");
                lbOK = false;
            }
        }

        String lsAge = jTextFieldAge.getText();

        if (lsAge.trim().equals("")) {
            lsbMessage.append("Age obligatoire<br>");
            lbOK = false;
        } else {
            int liAge = Integer.valueOf(lsAge);
            if (liAge < 0 || liAge > 125) {
                lsbMessage.append("Age improbable<br>");
                lbOK = false;
            } else {
                if (liAge >= 18) {
                    lsbMessage.append("Majeur<br>");
                } else {
                    lsbMessage.append("Mineur<br>");
                }
            }
        }

        lsbMessage.append(jComboBoxJours.getSelectedItem().toString());
        lsbMessage.append(" ");
        lsbMessage.append(jComboBoxMois.getSelectedItem().toString());
        lsbMessage.append(" ");
        lsbMessage.append(jComboBoxAnnees.getSelectedItem().toString());

        lsbMessage.append("</html>");
        jLabelMessage.setText(lsbMessage.toString());

//        System.out.println(lbOK);
        if (lbOK) {
            int noInscrit = 1;
            String lsPseudo = this.jTextFieldPseudo.getText();
            String lsMDP = this.jTextFieldMDP.getText();
            int liAge = Integer.valueOf(this.jTextFieldAge.getText());
            String lsDateInscription = jComboBoxJours.getSelectedItem() + " " + jComboBoxMois.getSelectedItem() + " " + jComboBoxAnnees.getSelectedItem();
            Inscrit inscrit = new Inscrit(noInscrit, lsPseudo, lsMDP, liAge, lsDateInscription);

            jLabelMessage.setText(inscrit.toString());
        }

    }//GEN-LAST:event_jButtonValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscriptionEtape7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscriptionEtape7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscriptionEtape7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscriptionEtape7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscriptionEtape7().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JComboBox jComboBoxAnnees;
    private javax.swing.JComboBox jComboBoxJours;
    private javax.swing.JComboBox jComboBoxMois;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldMDP;
    private javax.swing.JTextField jTextFieldPseudo;
    // End of variables declaration//GEN-END:variables
}
